@startuml DomainModel

class Restaurant
class Table
class Seat
class Action
class Arrive {
  requestedSeats
  timestamp
}
class Leave
class CustomerGroup {
  size
}

Restaurant *--> "1..n" Table

Table  *--> "2..6" Seat

Table o--> CustomerGroup : accomodates

Arrive -up-|> Action
Leave -up-|> Action
Arrive --> Seat: "reserves"
Leave --> Seat: "frees"

CustomerGroup --> Action


@enduml
