@startuml UseCases

actor CustomerGroup
actor Host

usecase Arrive
usecase Leave

usecase LocateGroup
usecase ArrangeTables

CustomerGroup --> Arrive
CustomerGroup --> Leave

Host --> LocateGroup
Host --> ArrangeTables

@enduml