@startuml UseCases

actor Client
actor Host

usecase RequestTable
usecase Leave

usecase LocateGroup
usecase ArrangeTables

Client --> RequestTable
Client --> Leave

Host --> LocateGroup
Host --> ArrangeTables

@enduml